/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './login';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from './login.service';
import * as import9 from 'ionic-angular/navigation/nav-controller';
import * as import10 from '@ionic/storage/es2015/storage';
import * as import11 from '@angular/core/src/metadata/view';
import * as import12 from '@angular/core/src/linker/component_factory';
import * as import13 from '../../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as import14 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import15 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import16 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import17 from 'ionic-angular/config/config';
import * as import18 from '@angular/core/src/linker/element_ref';
import * as import19 from 'ionic-angular/navigation/view-controller';
import * as import20 from 'ionic-angular/components/app/app';
import * as import21 from 'ionic-angular/components/toolbar/toolbar';
import * as import22 from 'ionic-angular/util/keyboard';
import * as import23 from '@angular/core/src/zone/ng_zone';
import * as import24 from 'ionic-angular/components/tabs/tabs';
import * as import25 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import26 from 'ionic-angular/components/navbar/navbar';
import * as import27 from 'ionic-angular/components/content/content';
export class Wrapper_LoginPage {
  context:import0.LoginPage;
  changed:boolean;
  constructor(p0:any,p1:any,p2:any) {
    this.changed = false;
    this.context = new import0.LoginPage(p0,p1,p2);
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
var renderType_LoginPage_Host:import2.RenderComponentType = (null as any);
class _View_LoginPage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _LoginPage_0_4:Wrapper_LoginPage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_LoginPage_Host0,renderType_LoginPage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('my-component',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_LoginPage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._LoginPage_0_4 = new Wrapper_LoginPage(this.parentInjector.get(import8.LoginService),this.parentInjector.get(import9.NavController),this.parentInjector.get(import10.Storage));
    this._appEl_0.initComponent(this._LoginPage_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._LoginPage_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.LoginPage) && (0 === requestNodeIndex))) { return this._LoginPage_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._LoginPage_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_LoginPage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_LoginPage_Host === (null as any))) { (renderType_LoginPage_Host = viewUtils.createRenderComponentType('',0,import11.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_LoginPage_Host0(viewUtils,parentInjector,declarationEl);
}
export const LoginPageNgFactory:import12.ComponentFactory<import0.LoginPage> = new import12.ComponentFactory<import0.LoginPage>('my-component',viewFactory_LoginPage_Host0,import0.LoginPage);
const styles_LoginPage:any[] = ['.custom-del-tel[_ngcontent-%COMP%] + span[_ngcontent-%COMP%]{\n                line-height: 50px;\n            }\n            .custom-del-psw[_ngcontent-%COMP%] + span[_ngcontent-%COMP%]{\n                line-height: 35px;\n            }'];
var renderType_LoginPage:import2.RenderComponentType = (null as any);
class _View_LoginPage0 extends import1.AppView<import0.LoginPage> {
  _text_0:any;
  _el_1:any;
  _Header_1_3:import13.Wrapper_Header;
  _text_2:any;
  _el_3:any;
  /*private*/ _appEl_3:import3.AppElement;
  _Navbar_3_4:import14.Wrapper_Navbar;
  _text_4:any;
  _el_5:any;
  /*private*/ _appEl_5:import3.AppElement;
  _ToolbarTitle_5_4:import15.Wrapper_ToolbarTitle;
  _text_6:any;
  _text_7:any;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  /*private*/ _appEl_10:import3.AppElement;
  _Content_10_4:import16.Wrapper_Content;
  _text_11:any;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _el_17:any;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _el_21:any;
  _text_22:any;
  _el_23:any;
  _text_24:any;
  _el_25:any;
  _text_26:any;
  _text_27:any;
  _el_28:any;
  _text_29:any;
  _el_30:any;
  _text_31:any;
  _text_32:any;
  _el_33:any;
  _text_34:any;
  _el_35:any;
  _text_36:any;
  _text_37:any;
  _text_38:any;
  _el_39:any;
  _text_40:any;
  _el_41:any;
  _text_42:any;
  _text_43:any;
  _text_44:any;
  _text_45:any;
  _text_46:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_LoginPage0,renderType_LoginPage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,' ',(null as any));
    this._el_1 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_1_3 = new import13.Wrapper_Header(this.parentInjector.get(import17.Config),new import18.ElementRef(this._el_1),this.renderer,this.parentInjector.get(import19.ViewController,(null as any)));
    this._text_2 = this.renderer.createText(this._el_1,'\n  ',(null as any));
    this._el_3 = this.renderer.createElement(this._el_1,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_3,'class','toolbar');
    this._appEl_3 = new import3.AppElement(3,1,this,this._el_3);
    var compView_3:any = import14.viewFactory_Navbar0(this.viewUtils,this.injector(3),this._appEl_3);
    this._Navbar_3_4 = new import14.Wrapper_Navbar(this.parentInjector.get(import20.App),this.parentInjector.get(import19.ViewController,(null as any)),this.parentInjector.get(import9.NavController,(null as any)),this.parentInjector.get(import17.Config),new import18.ElementRef(this._el_3),this.renderer);
    this._appEl_3.initComponent(this._Navbar_3_4.context,([] as any[]),compView_3);
    this._text_4 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_5 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_5 = new import3.AppElement(5,3,this,this._el_5);
    var compView_5:any = import15.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(5),this._appEl_5);
    this._ToolbarTitle_5_4 = new import15.Wrapper_ToolbarTitle(this.parentInjector.get(import17.Config),new import18.ElementRef(this._el_5),this.renderer,this.parentInjector.get(import21.Toolbar,(null as any)),this._Navbar_3_4.context);
    this._appEl_5.initComponent(this._ToolbarTitle_5_4.context,([] as any[]),compView_5);
    this._text_6 = this.renderer.createText((null as any),'\n      登录\n    ',(null as any));
    compView_5.create(this._ToolbarTitle_5_4.context,[([] as any[]).concat([this._text_6])],(null as any));
    this._text_7 = this.renderer.createText((null as any),'\n  ',(null as any));
    compView_3.create(this._Navbar_3_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_4,
        this._el_5,
        this._text_7
      ]
      )
    ]
    ,(null as any));
    this._text_8 = this.renderer.createText(this._el_1,'\n',(null as any));
    this._text_9 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_10 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this._appEl_10 = new import3.AppElement(10,(null as any),this,this._el_10);
    var compView_10:any = import16.viewFactory_Content0(this.viewUtils,this.injector(10),this._appEl_10);
    this._Content_10_4 = new import16.Wrapper_Content(this.parentInjector.get(import17.Config),new import18.ElementRef(this._el_10),this.renderer,this.parentInjector.get(import20.App),this.parentInjector.get(import22.Keyboard),this.parentInjector.get(import23.NgZone),this.parentInjector.get(import19.ViewController,(null as any)),this.parentInjector.get(import24.Tabs,(null as any)));
    this._appEl_10.initComponent(this._Content_10_4.context,([] as any[]),compView_10);
    this._text_11 = this.renderer.createText((null as any),'\n\n \n        ',(null as any));
    this._text_12 = this.renderer.createText((null as any),'\n\n \n        ',(null as any));
    this._el_13 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_13,'class','mui-content bgwh');
    this._text_14 = this.renderer.createText(this._el_13,'\n            ',(null as any));
    this._el_15 = this.renderer.createElement(this._el_13,'div',(null as any));
    this.renderer.setElementAttribute(this._el_15,'class','Line');
    this._text_16 = this.renderer.createText(this._el_13,'\n\n            ',(null as any));
    this._el_17 = this.renderer.createElement(this._el_13,'div',(null as any));
    this.renderer.setElementAttribute(this._el_17,'class','pct75 auto mui-input-row');
    this.renderer.setElementAttribute(this._el_17,'style','padding-top: 10px;');
    this._text_18 = this.renderer.createText(this._el_17,'\n                ',(null as any));
    this._el_19 = this.renderer.createElement(this._el_17,'input',(null as any));
    this.renderer.setElementAttribute(this._el_19,'class','login_its mui-input-clear custom-del-tel');
    this.renderer.setElementAttribute(this._el_19,'id','mobile');
    this.renderer.setElementAttribute(this._el_19,'maxlength','11');
    this.renderer.setElementAttribute(this._el_19,'placeholder','输入手机号码');
    this.renderer.setElementAttribute(this._el_19,'style','margin:0.5rem 0; border: none;');
    this.renderer.setElementAttribute(this._el_19,'type','tel');
    this.renderer.setElementAttribute(this._el_19,'value','');
    this._text_20 = this.renderer.createText(this._el_17,'\n\n                ',(null as any));
    this._el_21 = this.renderer.createElement(this._el_17,'div',(null as any));
    this.renderer.setElementAttribute(this._el_21,'class','Line');
    this._text_22 = this.renderer.createText(this._el_17,'\n                ',(null as any));
    this._el_23 = this.renderer.createElement(this._el_17,'div',(null as any));
    this.renderer.setElementAttribute(this._el_23,'class','mui-input-row');
    this._text_24 = this.renderer.createText(this._el_23,'\n                    ',(null as any));
    this._el_25 = this.renderer.createElement(this._el_23,'input',(null as any));
    this.renderer.setElementAttribute(this._el_25,'class','login_its mui-input-clear custom-del-psw');
    this.renderer.setElementAttribute(this._el_25,'id','password');
    this.renderer.setElementAttribute(this._el_25,'maxlength','18');
    this.renderer.setElementAttribute(this._el_25,'placeholder','请输入密码');
    this.renderer.setElementAttribute(this._el_25,'style','margin:0.5rem 0;border: none;');
    this.renderer.setElementAttribute(this._el_25,'type','password');
    this.renderer.setElementAttribute(this._el_25,'value','');
    this._text_26 = this.renderer.createText(this._el_23,'\n                ',(null as any));
    this._text_27 = this.renderer.createText(this._el_17,'\n                ',(null as any));
    this._el_28 = this.renderer.createElement(this._el_17,'div',(null as any));
    this.renderer.setElementAttribute(this._el_28,'class','Line');
    this._text_29 = this.renderer.createText(this._el_17,'\n                ',(null as any));
    this._el_30 = this.renderer.createElement(this._el_17,'div',(null as any));
    this.renderer.setElementAttribute(this._el_30,'class','tr');
    this.renderer.setElementAttribute(this._el_30,'id','forgetPwd');
    this.renderer.setElementAttribute(this._el_30,'style','margin-top: 1.6rem; margin-bottom: 1.6rem;');
    this._text_31 = this.renderer.createText(this._el_30,'\n                    忘记密码\n                ',(null as any));
    this._text_32 = this.renderer.createText(this._el_17,'\n                ',(null as any));
    this._el_33 = this.renderer.createElement(this._el_17,'div',(null as any));
    this._text_34 = this.renderer.createText(this._el_33,'\n                    ',(null as any));
    this._el_35 = this.renderer.createElement(this._el_33,'span',(null as any));
    this.renderer.setElementAttribute(this._el_35,'class','Btn Btn_middle Btn_orange Btn_radius Btn_disabled');
    this.renderer.setElementAttribute(this._el_35,'id','login');
    this._text_36 = this.renderer.createText(this._el_35,'登 录',(null as any));
    this._text_37 = this.renderer.createText(this._el_33,'\n                ',(null as any));
    this._text_38 = this.renderer.createText(this._el_17,'\n                ',(null as any));
    this._el_39 = this.renderer.createElement(this._el_17,'div',(null as any));
    this.renderer.setElementAttribute(this._el_39,'class','mt10');
    this._text_40 = this.renderer.createText(this._el_39,'\n                    ',(null as any));
    this._el_41 = this.renderer.createElement(this._el_39,'span',(null as any));
    this.renderer.setElementAttribute(this._el_41,'class','Btn Btn_middle Btn_white Btn_radius');
    this.renderer.setElementAttribute(this._el_41,'id','login_res');
    this._text_42 = this.renderer.createText(this._el_41,'注 册',(null as any));
    this._text_43 = this.renderer.createText(this._el_39,'\n                ',(null as any));
    this._text_44 = this.renderer.createText(this._el_17,'\n            ',(null as any));
    this._text_45 = this.renderer.createText(this._el_13,'\n        ',(null as any));
    this._text_46 = this.renderer.createText((null as any),'\n\n',(null as any));
    compView_10.create(this._Content_10_4.context,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_11,
        this._text_12,
        this._el_13,
        this._text_46
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_35,'click',this.eventHandler(this._handle_click_35_0.bind(this)));
    this.init(([] as any[]),[
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._text_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._text_37,
      this._text_38,
      this._el_39,
      this._text_40,
      this._el_41,
      this._text_42,
      this._text_43,
      this._text_44,
      this._text_45,
      this._text_46
    ]
    ,[disposable_0],([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import25.ToolbarTitle) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._ToolbarTitle_5_4.context; }
    if (((token === import26.Navbar) && ((3 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Navbar_3_4.context; }
    if (((token === import21.Header) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._Header_1_3.context; }
    if (((token === import27.Content) && ((10 <= requestNodeIndex) && (requestNodeIndex <= 46)))) { return this._Content_10_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Header_1_3.detectChangesInternal(this,this._el_1,throwOnChange);
    this._Navbar_3_4.detectChangesInternal(this,this._el_3,throwOnChange);
    if (this._ToolbarTitle_5_4.detectChangesInternal(this,this._el_5,throwOnChange)) { this._appEl_5.componentView.markAsCheckOnce(); }
    if (this._Content_10_4.detectChangesInternal(this,this._el_10,throwOnChange)) { this._appEl_10.componentView.markAsCheckOnce(); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = this._Navbar_3_4.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_3,'hidden',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this._Navbar_3_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_3,'statusbar-padding',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this._Content_10_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_10,'statusbar-padding',currVal_2);
      this._expr_2 = currVal_2;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_3_4.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Content_10_4.context.ngOnDestroy();
  }
  private _handle_click_35_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context._login(this._el_19.value,this._el_25.value)) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_LoginPage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.LoginPage> {
  if ((renderType_LoginPage === (null as any))) { (renderType_LoginPage = viewUtils.createRenderComponentType('',0,import11.ViewEncapsulation.Emulated,styles_LoginPage,{})); }
  return new _View_LoginPage0(viewUtils,parentInjector,declarationEl);
}