/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './myaccount';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
import * as import11 from '../../../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as import12 from '../../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import13 from '../../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import14 from '../../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import15 from 'ionic-angular/config/config';
import * as import16 from '@angular/core/src/linker/element_ref';
import * as import17 from 'ionic-angular/navigation/view-controller';
import * as import18 from 'ionic-angular/components/app/app';
import * as import19 from 'ionic-angular/components/toolbar/toolbar';
import * as import20 from 'ionic-angular/util/keyboard';
import * as import21 from '@angular/core/src/zone/ng_zone';
import * as import22 from 'ionic-angular/components/tabs/tabs';
import * as import23 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import24 from 'ionic-angular/components/navbar/navbar';
import * as import25 from 'ionic-angular/components/content/content';
export class Wrapper_MyAccountPage {
  context:import0.MyAccountPage;
  changed:boolean;
  constructor(p0:any) {
    this.changed = false;
    this.context = new import0.MyAccountPage(p0);
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
var renderType_MyAccountPage_Host:import2.RenderComponentType = (null as any);
class _View_MyAccountPage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _MyAccountPage_0_4:Wrapper_MyAccountPage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_MyAccountPage_Host0,renderType_MyAccountPage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('my-component',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_MyAccountPage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._MyAccountPage_0_4 = new Wrapper_MyAccountPage(this.parentInjector.get(import8.NavController));
    this._appEl_0.initComponent(this._MyAccountPage_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._MyAccountPage_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.MyAccountPage) && (0 === requestNodeIndex))) { return this._MyAccountPage_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._MyAccountPage_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_MyAccountPage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_MyAccountPage_Host === (null as any))) { (renderType_MyAccountPage_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_MyAccountPage_Host0(viewUtils,parentInjector,declarationEl);
}
export const MyAccountPageNgFactory:import10.ComponentFactory<import0.MyAccountPage> = new import10.ComponentFactory<import0.MyAccountPage>('my-component',viewFactory_MyAccountPage_Host0,import0.MyAccountPage);
const styles_MyAccountPage:any[] = ([] as any[]);
var renderType_MyAccountPage:import2.RenderComponentType = (null as any);
class _View_MyAccountPage0 extends import1.AppView<import0.MyAccountPage> {
  _el_0:any;
  _Header_0_3:import11.Wrapper_Header;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import3.AppElement;
  _Navbar_2_4:import12.Wrapper_Navbar;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import3.AppElement;
  _ToolbarTitle_4_4:import13.Wrapper_ToolbarTitle;
  _text_5:any;
  _text_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  /*private*/ _appEl_9:import3.AppElement;
  _Content_9_4:import14.Wrapper_Content;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _el_17:any;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _el_21:any;
  _text_22:any;
  _el_23:any;
  _text_24:any;
  _text_25:any;
  _text_26:any;
  _text_27:any;
  _el_28:any;
  _text_29:any;
  _el_30:any;
  _text_31:any;
  _el_32:any;
  _text_33:any;
  _text_34:any;
  _text_35:any;
  _text_36:any;
  _el_37:any;
  _text_38:any;
  _el_39:any;
  _text_40:any;
  _el_41:any;
  _text_42:any;
  _text_43:any;
  _text_44:any;
  _text_45:any;
  _text_46:any;
  _text_47:any;
  _el_48:any;
  _text_49:any;
  _el_50:any;
  _text_51:any;
  _el_52:any;
  _text_53:any;
  _el_54:any;
  _text_55:any;
  _text_56:any;
  _text_57:any;
  _text_58:any;
  _text_59:any;
  _text_60:any;
  _text_61:any;
  _text_62:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_MyAccountPage0,renderType_MyAccountPage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_0_3 = new import11.Wrapper_Header(this.parentInjector.get(import15.Config),new import16.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import17.ViewController,(null as any)));
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','toolbar');
    this._appEl_2 = new import3.AppElement(2,0,this,this._el_2);
    var compView_2:any = import12.viewFactory_Navbar0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Navbar_2_4 = new import12.Wrapper_Navbar(this.parentInjector.get(import18.App),this.parentInjector.get(import17.ViewController,(null as any)),this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import15.Config),new import16.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Navbar_2_4.context,([] as any[]),compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_4 = new import3.AppElement(4,2,this,this._el_4);
    var compView_4:any = import13.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(4),this._appEl_4);
    this._ToolbarTitle_4_4 = new import13.Wrapper_ToolbarTitle(this.parentInjector.get(import15.Config),new import16.ElementRef(this._el_4),this.renderer,this.parentInjector.get(import19.Toolbar,(null as any)),this._Navbar_2_4.context);
    this._appEl_4.initComponent(this._ToolbarTitle_4_4.context,([] as any[]),compView_4);
    this._text_5 = this.renderer.createText((null as any),'\n      账户\n    ',(null as any));
    compView_4.create(this._ToolbarTitle_4_4.context,[([] as any[]).concat([this._text_5])],(null as any));
    this._text_6 = this.renderer.createText((null as any),'\n  ',(null as any));
    compView_2.create(this._Navbar_2_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_3,
        this._el_4,
        this._text_6
      ]
      )
    ]
    ,(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_8 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_9 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this._appEl_9 = new import3.AppElement(9,(null as any),this,this._el_9);
    var compView_9:any = import14.viewFactory_Content0(this.viewUtils,this.injector(9),this._appEl_9);
    this._Content_9_4 = new import14.Wrapper_Content(this.parentInjector.get(import15.Config),new import16.ElementRef(this._el_9),this.renderer,this.parentInjector.get(import18.App),this.parentInjector.get(import20.Keyboard),this.parentInjector.get(import21.NgZone),this.parentInjector.get(import17.ViewController,(null as any)),this.parentInjector.get(import22.Tabs,(null as any)));
    this._appEl_9.initComponent(this._Content_9_4.context,([] as any[]),compView_9);
    this._text_10 = this.renderer.createText((null as any),'\n\n\n\n',(null as any));
    this._el_11 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_11,'class','mui-content bgwh');
    this._text_12 = this.renderer.createText(this._el_11,'\n            ',(null as any));
    this._el_13 = this.renderer.createElement(this._el_11,'div',(null as any));
    this.renderer.setElementAttribute(this._el_13,'class','Line');
    this._text_14 = this.renderer.createText(this._el_11,'\n            ',(null as any));
    this._el_15 = this.renderer.createElement(this._el_11,'div',(null as any));
    this.renderer.setElementAttribute(this._el_15,'class','auto');
    this._text_16 = this.renderer.createText(this._el_15,'\n                ',(null as any));
    this._el_17 = this.renderer.createElement(this._el_15,'ul',(null as any));
    this.renderer.setElementAttribute(this._el_17,'class','mui-table-view');
    this.renderer.setElementAttribute(this._el_17,'style','padding-left: 1rem; padding-right: 1rem;');
    this._text_18 = this.renderer.createText(this._el_17,'\n                    ',(null as any));
    this._el_19 = this.renderer.createElement(this._el_17,'li',(null as any));
    this.renderer.setElementAttribute(this._el_19,'class','mui-table-view-cell');
    this._text_20 = this.renderer.createText(this._el_19,'\n                        ',(null as any));
    this._el_21 = this.renderer.createElement(this._el_19,'a',(null as any));
    this.renderer.setElementAttribute(this._el_21,'class','mui-navigate-right');
    this.renderer.setElementAttribute(this._el_21,'id','ad_lean');
    this._text_22 = this.renderer.createText(this._el_21,'学习支出\n                            ',(null as any));
    this._el_23 = this.renderer.createElement(this._el_21,'i',(null as any));
    this.renderer.setElementAttribute(this._el_23,'class','update  C_3');
    this.renderer.setElementAttribute(this._el_23,'id','allExpenses');
    this.renderer.setElementAttribute(this._el_23,'style','float: right; padding-right: 1.5rem;font-style: normal;');
    this._text_24 = this.renderer.createText(this._el_23,'￥0.00',(null as any));
    this._text_25 = this.renderer.createText(this._el_21,'\n                        ',(null as any));
    this._text_26 = this.renderer.createText(this._el_19,'\n                    ',(null as any));
    this._text_27 = this.renderer.createText(this._el_17,'\n                    ',(null as any));
    this._el_28 = this.renderer.createElement(this._el_17,'li',(null as any));
    this.renderer.setElementAttribute(this._el_28,'class','mui-table-view-cell');
    this._text_29 = this.renderer.createText(this._el_28,'\n                        ',(null as any));
    this._el_30 = this.renderer.createElement(this._el_28,'a',(null as any));
    this.renderer.setElementAttribute(this._el_30,'class','mui-navigate');
    this._text_31 = this.renderer.createText(this._el_30,'课程支付\n                            ',(null as any));
    this._el_32 = this.renderer.createElement(this._el_30,'i',(null as any));
    this.renderer.setElementAttribute(this._el_32,'class','update  C_3');
    this.renderer.setElementAttribute(this._el_32,'id','coursesExpense');
    this.renderer.setElementAttribute(this._el_32,'style','float: right; padding-right: 1.5rem;font-style: normal;');
    this._text_33 = this.renderer.createText(this._el_32,'￥0.00',(null as any));
    this._text_34 = this.renderer.createText(this._el_30,'\n                        ',(null as any));
    this._text_35 = this.renderer.createText(this._el_28,'\n                    ',(null as any));
    this._text_36 = this.renderer.createText(this._el_17,'\n                    ',(null as any));
    this._el_37 = this.renderer.createElement(this._el_17,'li',(null as any));
    this.renderer.setElementAttribute(this._el_37,'class','mui-table-view-cell');
    this._text_38 = this.renderer.createText(this._el_37,'\n                        ',(null as any));
    this._el_39 = this.renderer.createElement(this._el_37,'a',(null as any));
    this.renderer.setElementAttribute(this._el_39,'class','mui-navigate');
    this._text_40 = this.renderer.createText(this._el_39,'问道支付\n                        ',(null as any));
    this._el_41 = this.renderer.createElement(this._el_39,'i',(null as any));
    this.renderer.setElementAttribute(this._el_41,'class','update  C_3');
    this.renderer.setElementAttribute(this._el_41,'id','faqExpense');
    this.renderer.setElementAttribute(this._el_41,'style','float: right; padding-right: 1.5rem; font-style: normal;');
    this._text_42 = this.renderer.createText(this._el_41,'￥0.00',(null as any));
    this._text_43 = this.renderer.createText(this._el_39,'\n                        ',(null as any));
    this._text_44 = this.renderer.createText(this._el_37,'\n                    ',(null as any));
    this._text_45 = this.renderer.createText(this._el_17,'\n',(null as any));
    this._text_46 = this.renderer.createText(this._el_17,'\n                ',(null as any));
    this._text_47 = this.renderer.createText(this._el_15,'\n                ',(null as any));
    this._el_48 = this.renderer.createElement(this._el_15,'ul',(null as any));
    this.renderer.setElementAttribute(this._el_48,'class','mui-table-view');
    this.renderer.setElementAttribute(this._el_48,'style','margin-top:0.5rem;padding-left: 1rem; padding-right: 1rem;');
    this._text_49 = this.renderer.createText(this._el_48,'\n                    ',(null as any));
    this._el_50 = this.renderer.createElement(this._el_48,'li',(null as any));
    this.renderer.setElementAttribute(this._el_50,'class','mui-table-view-cell');
    this._text_51 = this.renderer.createText(this._el_50,'\n                        ',(null as any));
    this._el_52 = this.renderer.createElement(this._el_50,'a',(null as any));
    this.renderer.setElementAttribute(this._el_52,'class','mui-navigate');
    this._text_53 = this.renderer.createText(this._el_52,'我的收入\n                            ',(null as any));
    this._el_54 = this.renderer.createElement(this._el_52,'i',(null as any));
    this.renderer.setElementAttribute(this._el_54,'class','update  C_3');
    this.renderer.setElementAttribute(this._el_54,'id','allIncome');
    this.renderer.setElementAttribute(this._el_54,'style','float: right; padding-right: 1.5rem; font-style: normal;');
    this._text_55 = this.renderer.createText(this._el_54,'￥0.00',(null as any));
    this._text_56 = this.renderer.createText(this._el_52,'\n                            \n                        ',(null as any));
    this._text_57 = this.renderer.createText(this._el_50,'\n                    ',(null as any));
    this._text_58 = this.renderer.createText(this._el_48,'\n                ',(null as any));
    this._text_59 = this.renderer.createText(this._el_15,'\n            ',(null as any));
    this._text_60 = this.renderer.createText(this._el_11,'\n            \n        ',(null as any));
    this._text_61 = this.renderer.createText((null as any),'\n\n\n        ',(null as any));
    compView_9.create(this._Content_9_4.context,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_10,
        this._el_11,
        this._text_61
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._text_62 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._text_25,
      this._text_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._text_34,
      this._text_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._el_39,
      this._text_40,
      this._el_41,
      this._text_42,
      this._text_43,
      this._text_44,
      this._text_45,
      this._text_46,
      this._text_47,
      this._el_48,
      this._text_49,
      this._el_50,
      this._text_51,
      this._el_52,
      this._text_53,
      this._el_54,
      this._text_55,
      this._text_56,
      this._text_57,
      this._text_58,
      this._text_59,
      this._text_60,
      this._text_61,
      this._text_62
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import23.ToolbarTitle) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._ToolbarTitle_4_4.context; }
    if (((token === import24.Navbar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._Navbar_2_4.context; }
    if (((token === import19.Header) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Header_0_3.context; }
    if (((token === import25.Content) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 61)))) { return this._Content_9_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Header_0_3.detectChangesInternal(this,this._el_0,throwOnChange);
    this._Navbar_2_4.detectChangesInternal(this,this._el_2,throwOnChange);
    if (this._ToolbarTitle_4_4.detectChangesInternal(this,this._el_4,throwOnChange)) { this._appEl_4.componentView.markAsCheckOnce(); }
    if (this._Content_9_4.detectChangesInternal(this,this._el_9,throwOnChange)) { this._appEl_9.componentView.markAsCheckOnce(); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = this._Navbar_2_4.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_2,'hidden',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this._Navbar_2_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_2,'statusbar-padding',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this._Content_9_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_9,'statusbar-padding',currVal_2);
      this._expr_2 = currVal_2;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_2_4.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Content_9_4.context.ngOnDestroy();
  }
}
export function viewFactory_MyAccountPage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.MyAccountPage> {
  if ((renderType_MyAccountPage === (null as any))) { (renderType_MyAccountPage = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,styles_MyAccountPage,{})); }
  return new _View_MyAccountPage0(viewUtils,parentInjector,declarationEl);
}